services:
  - type: web
    name: studenttasker-backend
    runtime: node
    plan: free  
    region: singapore
    buildCommand: npm ci && npm run build:render
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false  # You'll set this manually in Render dashboard
    autoDeploy: true